### ISSUE TITLE
Please include in documentation how to install and what dependencies are required!

### ISSUE THREAD

**Issue by Dr-Drive** [zinka/arraytool#1]
Hello,
The library does look very interesting but for non git/python experts it might be challenging to get the project working. Could you please shed some light on how to install the libraries using cygwin/eps python on windows?

**Comment by zinka** [comment]
Hi,

First of all, thank you for showing interest in arraytool package. Though functional, this package has been under construction for a long time. Recently, I have added a few more functions to the existing modules. However, I can share them only after I submit my work to some journal paper.

Coming to your question regarding the installation, I am not very good at building binaries for installation. However, you can use all the functions provided in "src folder" by simply downloading the package from GitHub and run them by copying into your own packages or modules. After copying, please go through the following link for the basic usage of arraytool:
http://zinka.github.com/arraytool/tutorial.html

As for the dependencies, you need the following packages:
numpy, matplotlib, mayavi, scipy, mpmath, sympy

If you run into any trouble  while running the examples, please feel free to contact.

Regards,
zinka

**Comment by Dr-Drive** [comment]
Thanks!
I was able to run all the examples by copying the libraries to the project folder...
I was also able to implement some beam steering by setting the feed to a complex matrix with incremental phase difference per element. It works quite well =)

**Comment by Dr-Drive** [comment]
By the way, the best way to make the package work on windows is to use a full install of Python(x,y), thanks again for sharing!
